config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  #devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout'}
  
  scope "(:locale)", locale: /en|uk/ do
  #scope "/:locale" do
    resources :articles, :users
    get '/about', to: 'pages#about', as: :about
    get '/service', to: 'pages#service', as: :service
    get '/contacts', to: 'pages#contacts', as: :contacts
    #get '/articles', to: 'articles#articles', as: :articles

    root 'articles#index'
  end
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  #get '/:locale' => 'articles#index'
  #get '/:locale', to: "pages#about"
  #get '/:locale', to: "pages#contacts"
  #get '/:locale', to: "pages#service"

  #root "articles#index"
  #get "about", to: "pages#about"
  #get "contacts", to: "pages#contacts"
  #get "service", to: "pages#service"
 
  
  resources :articles do
    resources :comments
  end


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
    include Visible
    has_rich_text :content

    has_many :comments, dependent: :destroy

    after_validation :set_slug, only: [:create, :update]
    
    def to_param
        #"#{id}-#{slug}"
        [id, slug].join("-")
    end
  
    validates :title, presence: true
    validates :content, presence: true, length: { minimum: 10 }


    
    scope :sorted, -> { order(arel_table[:published_at].desc.nulls_last).order(updated_at: :desc)}
    scope :draft, -> { where(published_at: nil)}
    scope :published, -> { where("published_at <= ?", Date.current)}
    scope :scheduled, -> { where("published_at > ?", Date.current)}

    def translated_status
        I18n.t(status, :scope => 'status')
    end

    def draft?
        published_at.nil?
    end

    def published?
        published_at? && published_at <= Date.current
    end

    def scheduled?
        published_at? && published_at > Date.current
    end
    private
        def set_slug
            self.slug = title.to_s.parameterize
        end 
end

app/models/comment.rb
class Comment < ApplicationRecord
  include Visible
  has_rich_text :content
  belongs_to :article
end

app/models/concerns/visible.rb
module Visible
    extend ActiveSupport::Concern
  
    VALID_STATUSES = ['public', 'private', 'archived']
  
    included do
      validates :status, inclusion: { in: VALID_STATUSES }
    end
  
    class_methods do
      def public_count
        where(status: 'public').count
      end
    end
  
    def archived?
      status == 'archived'
    end
end
  

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
    def default_url_options
        { locale: I18n.locale }
    end   
    
    around_action :switch_locale

    def switch_locale(&action)
      locale = params[:locale] || I18n.default_locale
      I18n.with_locale(locale, &action)
    end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_article, except: [:index, :new, :create]


  def index
    @articles = user_signed_in? ? Article.sorted : Article.published.sorted
  end

  def show
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to @article
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @article.update(article_params)
      redirect_to @article
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @article.destroy
    redirect_to root_path, status: :see_other
  end
  rescue ActiveRecord::RecordNotFound
    redirect_to root_path
  end
  
  private
    def article_params
      params.require(:article).permit(:title, :content, :status, :published_at)
    end
  
    def set_article
      @article = user_signed_in? ? Article.find(params[:id]) : Article.published.find(params[:id])
            
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :authenticate_user!, except: [:index, :show]
    
      def create
        @article = Article.find(params[:article_id])
        @comment = @article.comments.create(comment_params)
        redirect_to article_path(@article)
      end
    
      def destroy
        @article = Article.find(params[:article_id])
        @comment = @article.comments.find(params[:id])
        @comment.destroy
        redirect_to article_path(@article), status: :see_other
      end
    
      private
        def comment_params
          params.require(:comment).permit(:commenter, :content, :status)
        end
  end
    

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def contacts
  end

  def service
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_url
    "#{request.protocol}#{request.host_with_port}#{request.fullpath}"
  end

  def current_site
    @current_site = t('it_exchange')
  end

  def current_title
    title = []
    title << current_site
    if content_for?(:title)
      title << content_for(:title)
    else
      title << params[:controller].split("/").last.titleize
    end
    title.uniq.join(" | ")
  end

  def title(elements=[])
    content_for :title, elements.to_a.compact.map{ |a| a.try(:name) || a.try(:title) || a.try(:id) || a.to_s.capitalize }.join(" | ")
  end

  def description(description="")
    content_for :description, description
  end

  def sanitize(content)
    ActionController::Base.helpers.sanitize(content)
  end

  def strip_tags_and_entities(string)
    if string.present?
      stripped = strip_tags(string)
      decoded = HTMLEntities.new.decode(stripped)
      decoded.squish.gsub(%r{/</?[^>]*>/}, "")
    end
  end

  def route_exists?(path)
    begin
      recognize_path = Rails.application.routes.recognize_path(path, method: :get)
      recognize_path.present? && recognize_path[:action] != "route_not_found"
    rescue StandardError
      false
    end
  end

  def content_for_or(name, default)
    if content_for?(name)
      content_for(name)
    else
      default
    end
  end

  def body_class(params)
    body = []
    return unless params[:controller]
    if params[:controller].include?("/")
      body << params[:controller].split("/").first
      body << params[:controller].gsub("/", "-")
    else
      body << params[:controller]
    end
    if params[:controller].include?("/")
      body << "#{params[:controller].gsub('/', '-')}-#{params[:action]}"
    else
      body << "#{params[:controller]}-#{params[:action]}"
    end
    if params.key?(:page)
      body << "#{params[:controller]}-#{params[:action]}-#{params[:page]}"
    end
    body.join(" ")
  end
  
  #Devise helper
  def resource_name
    :user
  end
  
  def resource
    @resource ||= User.new
  end
  
  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
  
  def resource_class
    devise_mapping.to
  end

end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/action_text/attachables/_content_attachment.html.erb
<figure class="attachment attachment--content attachment--<%= content_attachment.name %>">
    <%= render "action_text/attachables/content_attachments/#{content_attachment.name.underscore}" %>
</figure>

app/views/action_text/attachables/content_attachments/_horizontal_rule.html.erb
<hr>

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/articles/_form.html.erb
<%= form_with model: article do |form| %>
  <div class="mb-3">
    <%= form.label :title, class: "form-label", for: "InputTitle" %><br>
    <%= form.text_field :title, class: "form-control", id: "InputTitle" %>
    <% article.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :content, class: "form-label", for: "InputBody" %><br>
    <%= form.rich_text_area :content, class: "form-control", id: "InputBody" %><br>
    <% article.errors.full_messages_for(:content).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
  <div class="input-group mb-3 grid" style="--bs-columns: 3;">
    <%= form.label t('status'), class: "input-group-text" %>
    <%= form.select(:status, [
                                [I18n.t("public"), 'public'],
                                [I18n.t('private'), 'private'],
                                [I18n.t('archived'), 'archived']
                              ], {selected: [I18n.t('public'),'public']}, {:class=> "form-select"}) %>
    <%= form.label t('published_at'), class: "input-group-text"%>
    <%= form.date_select(:published_at, {include_blank:true}, {:class => 'form-select'}) %>
    <%= form.submit t('edit')+' '+t('article'), class: "btn btn-outline-secondary"%>
    <%= link_to t('devise.shared.links.back'), :back, class: "btn btn-outline-secondary" %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1><%= t('edit')+' '+t('article')%></h1>

<%= render "form", article: @article %>

app/views/articles/index.html.erb
<h1><%=t('articles')%></h1>
<div class="row mb-2">
<% @articles.each do |article| %>
  <% unless article.archived? %>
    <div class="col-md-4">
      <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
        <div class="col p-2 d-flex flex-column position-static">
          <% if article.draft? %>
            <strong class="btn btn-secondary"><%=t('draft')%></strong>
          <%elsif article.scheduled?%>
            <strong class="btn btn-info"><%=t('scheduled')%></strong>
          <%end%>
          <h5 class="mb-0"><%= link_to article.title, article %></h5>
          <div class="mb-1 text-body-secondary"><%= article.created_at.strftime("%B %d")%></div>
          <p class="card-text mb-auto">
            <%= truncate((raw article.content.to_plain_text), length: 100)%>
          </p>
            <%= link_to t("continue_reading"), article, class: "icon-link gap-1 icon-link-hover stretched-link"%>
        </div>
        <div class="col-auto d-none d-lg-block">
          <svg class="bd-placeholder-img" width="200" height="250" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"></rect><text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text></svg>
        </div>
      </div>
    </div>
  <%end%>
<% end %>
    <%= link_to t("new_article"), new_article_path, class:"btn btn-success" %>  
</div>

app/views/articles/new.html.erb
<h1><%=t('new_article')%> </h1>

<%= render "form", article: @article %>

app/views/articles/show.html.erb
<div class="col-8 offset-2 col-sm-8 offset-sm-2">
  <h3 mb-3 fw-normal><%= @article.title %></h3>
      <%= @article.content %>
      <% if user_signed_in?%>
          <%= link_to t('edit'), edit_article_path(@article), class: "btn btn-outline-secondary my-3"%>
          <%= link_to t('destroy'), article_path(@article), data: {
                              turbo_method: :delete,
                              turbo_confirm: "Are you sure?"
                            }, class: "btn btn-outline-secondary my-3"%>
          <h4 mb-3 fw-normal><%=t('comments')%></h4>
          <%= render @article.comments %>

          <h5 mb-3 fw-normal><%=t('add_a_comment')%>:</h5>
          <%= render 'comments/form' %>

      <%end%>
  </div>

app/views/comments/_comment.html.erb
<% unless comment.archived? %>
  <p>
    <strong><%=t('commenter')%>:</strong>
    <%= comment.commenter %>
  </p>

  <p>
    <strong><%=t('comment')%>:</strong>
    <%= comment.content%>
  </p>

  <p>
    <%= link_to t('destroy')+' '+t('comment'), [comment.article, comment], data: {
                  turbo_method: :delete,
                  turbo_confirm: "Are you sure?"
                }, class: "btn btn-outline-secondary"%>
  </p>
<% end %>

app/views/comments/_form.html.erb
<%= form_with model: [ @article, @article.comments.build ] do |form| %>
  <div class="input-group">
      <%= form.label t('commenter'), class:"input-group-text"%>
      <%= form.text_field :commenter, :value=>current_user.email, class:"form-control" %>
  </div>
    <%= form.label :content%>
    <%= form.rich_text_area :content, class:"form-control"%>
  <div class="input-group mt-3 mb-3">
    <%= form.label t('status'), class:"input-group-text" %>
    <%= form.select(:status, [
                                [I18n.t("public"), 'public'],
                                [I18n.t('private'), 'private'],
                                [I18n.t('archived'), 'archived']
                              ], {selected: [I18n.t('public'),'public']}, {:class=> "form-select"}) %>
    <%= form.submit t('create')+' '+t('comment'), class: "btn btn-outline-secondary"%>
  </div>
    
<% end %>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="<%= I18n.locale %>">
  <head>
    <%= render 'partials/metatags' %>
  </head>
  <body class="<%= body_class(params) %>">
    <nav class="d-block">
      <%= render 'partials/navbar' %>
    </nav>
    <main role="main" class="main m-3">
      <div class="container-fluid">
        <%= render 'partials/messages' %>
        <%= yield %>
      </div>
    </main>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contacts.html.erb
<h1>Pages#contacts</h1>
<p>Find me in app/views/pages/contacts.html.erb</p>

app/views/pages/service.html.erb
<h1>Pages#service</h1>
<p>Find me in app/views/pages/service.html.erb</p>

app/views/partials/_change_locale.html.erb
<li><%= link_to 'EN', root_path(locale: :en), class: "nav-link"%></li>
<li class="nav-link"><i class="bi bi-signpost-split pt-2"></i></li>
<li><%= link_to 'UA', root_path(locale: :uk), class: "nav-link" %></li>

app/views/partials/_messages.html.erb
<% colors = { 
  info: "info",
  notice: "success",
  success: "success",
  warning: "warning",
  error: "danger"
}.freeze %>

<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
  <div class="alert alert-<%= colors[name.to_sym] || "info" %> alert-dismissible fade show" role="alert">
    <%= content_tag :div, t(msg) %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
  <% end %>
<% end %>

app/views/partials/_metatags.html.erb
<title><%=h sanitize current_title %></title>
<link rel="canonical" href="<%=h current_url %>" />
<% if content_for?(:image) -%>
<link rel="image_src" href="<%= content_for(:image) %>">
<% end %>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="robots" content="<%=h content_for_or(:robot, 'INDEX,FOLLOW') %>"/>
<meta name="description" content="<%=h content_for_or(:description, '') %>"/>
<meta name="keywords" content="<%=h content_for_or(:keywords, '') %>">
<meta name="theme-color" content="#777777">
<meta property="og:url" content="<%=h current_url %>" />
<meta property="og:site_name" content="<%= current_site %>" />
<meta property="og:type" content="<%=h content_for_or(:type, 'website') %>">
<meta property="og:title" content="<%=h current_title %>" />
<meta property="og:description" content="<%=h content_for_or(:description, '') %>" />
<% if content_for?(:image) -%>
<meta property="og:image" content="<%= content_for(:image) %>" />
<% end %>
<% if content_for?(:video) -%>
<meta property="og:video" content="<%= content_for(:video) %>" />
<% end %>
<meta name="twitter:card" content="summary" />
<% if ENV['APP_TWITTER'].present? %>
<meta name="twitter:site" content="<%= ENV['APP_TWITTER'] %>"/>
<meta name="twitter:creator" content="<%= ENV['APP_TWITTER'] %>"/>
<% end %>
<meta name="twitter:title" content="<%=h current_title %>"/>
<meta name="twitter:description" content="<%=h content_for_or(:description, '') %>"/>
<meta name="twitter:url" content="<%=h current_url %>"/>
<% if content_for?(:image) -%>
<meta name="twitter:image" content="<%= content_for(:image) %>"/>
<% end %>
<%= auto_discovery_link_tag(:rss, content_for(:rss), {title: "RSS Feed"}) if content_for?(:rss) %>
<%= auto_discovery_link_tag(:atom, content_for(:atom), {title: "Atom Feed"}) if content_for?(:atom) %>
<%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
<%= stylesheet_link_tag "actiontext", "data-turbo-track": "reload" %>
<%= javascript_importmap_tags %>
<%= csrf_meta_tags %>
<%= csp_meta_tag %>
<%= action_cable_meta_tag %>

app/views/partials/_navbar.html.erb
<nav id="navbar" class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to current_site, root_path, title: current_site, class: 'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarContent" aria-controls="navbarContent" aria-expanded="false" aria-label="Menu">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarContent">
      <ul class="navbar-nav me-auto">
        <li><%= link_to t('about_us'), about_path, class: "nav-link" %></li>
        <li><%= link_to t('service'), service_path, class: "nav-link" %></li>
        <li><%= link_to t('contacts'), contacts_path, class: "nav-link" %></li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <%=t("articles")%>
          </a>
          <%= content_tag(:ul, class:'dropdown-menu') do %>
            <%if user_signed_in?%>
              <% Article.find_each do |article|%>
                <% unless article.archived? %>
                  <%= content_tag(:li, (link_to article.title, article, class: "dropdown-item"))%>                
                <%end%>
              <%end%>
            <%else%>
              <% Article.published.find_each do |article|%>
                <% unless article.archived? %>
                  <%= content_tag(:li, (link_to article.title, article, class: "dropdown-item"))%>                
                <%end%>
              <%end%>           
            <%end%>
          <%end%>
        </li>
        <%= render 'partials/change_locale' %>
      </ul>
          
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit"><i class="bi bi-search"></i></button>
      </form>
      <% if user_signed_in? %>
        <%= link_to current_user.email, edit_user_registration_path, class:"px-1 mx-1"%>
        <%= button_to "Вийти", destroy_user_session_path, method: :delete, class:"btn btn-outline-secondary px-1 mx-1"%>
      <% else %>
        <div class="dropdown px-1">
          <button class="btn btn-outline-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
            Увійти
          </button>
          <ul class="dropdown-menu dropdown-menu-end px-1" style="width:21rem">
            <%=render 'users/sessions/new'%>
          </ul>
        </div>
        <div class="grid text-center">
          <%= link_to "Стати виконавцем", new_user_registration_path, class:"btn btn-outline-primary px-1 mx-1"%>
        </div>
      <% end %>
    </div>
  </div>
</nav>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false" class="alert alert-warning alert-dismissible fade show" role="alert">
    <strong>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </strong>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to t(".sign_in"), new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to t(".sign_up"), new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to t(".forgot_your_password"), new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to t('.didn_t_receive_confirmation_instructions'), new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to t('.didn_t_receive_unlock_instructions'), new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to t('.sign_in_with_provider', provider: OmniAuth::Utils.camelize(provider)), omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>